// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	OriginalTokens int32                  `protobuf:"varint,2,opt,name=original_tokens,json=originalTokens,proto3" json:"original_tokens,omitempty"`
	FilteredTokens int32                  `protobuf:"varint,3,opt,name=filtered_tokens,json=filteredTokens,proto3" json:"filtered_tokens,omitempty"`
	DurationMs     int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ExitCode       int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	FilterMode     string                 `protobuf:"bytes,6,opt,name=filter_mode,json=filterMode,proto3" json:"filter_mode,omitempty"`
	SessionId      string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *RecordRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RecordRequest) GetOriginalTokens() int32 {
	if x != nil {
		return x.OriginalTokens
	}
	return 0
}

func (x *RecordRequest) GetFilteredTokens() int32 {
	if x != nil {
		return x.FilteredTokens
	}
	return 0
}

func (x *RecordRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecordRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RecordRequest) GetFilterMode() string {
	if x != nil {
		return x.FilterMode
	}
	return ""
}

func (x *RecordRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *RecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetMetricsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetMetricsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalCommands    int64                  `protobuf:"varint,1,opt,name=total_commands,json=totalCommands,proto3" json:"total_commands,omitempty"`
	TotalTokensSaved int64                  `protobuf:"varint,2,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	TotalTokensIn    int64                  `protobuf:"varint,3,opt,name=total_tokens_in,json=totalTokensIn,proto3" json:"total_tokens_in,omitempty"`
	TotalTokensOut   int64                  `protobuf:"varint,4,opt,name=total_tokens_out,json=totalTokensOut,proto3" json:"total_tokens_out,omitempty"`
	AverageSavings   float64                `protobuf:"fixed64,5,opt,name=average_savings,json=averageSavings,proto3" json:"average_savings,omitempty"`
	P50LatencyMs     float64                `protobuf:"fixed64,6,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,7,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	TopFilters       []*FilterUsage         `protobuf:"bytes,8,rep,name=top_filters,json=topFilters,proto3" json:"top_filters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsResponse) GetTotalCommands() int64 {
	if x != nil {
		return x.TotalCommands
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTokensIn() int64 {
	if x != nil {
		return x.TotalTokensIn
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTokensOut() int64 {
	if x != nil {
		return x.TotalTokensOut
	}
	return 0
}

func (x *GetMetricsResponse) GetAverageSavings() float64 {
	if x != nil {
		return x.AverageSavings
	}
	return 0
}

func (x *GetMetricsResponse) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *GetMetricsResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *GetMetricsResponse) GetTopFilters() []*FilterUsage {
	if x != nil {
		return x.TopFilters
	}
	return nil
}

type FilterUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterName    string                 `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AvgSavings    float64                `protobuf:"fixed64,3,opt,name=avg_savings,json=avgSavings,proto3" json:"avg_savings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterUsage) Reset() {
	*x = FilterUsage{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterUsage) ProtoMessage() {}

func (x *FilterUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterUsage.ProtoReflect.Descriptor instead.
func (*FilterUsage) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *FilterUsage) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *FilterUsage) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FilterUsage) GetAvgSavings() float64 {
	if x != nil {
		return x.AvgSavings
	}
	return 0
}

type GetEconomicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEconomicsRequest) Reset() {
	*x = GetEconomicsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEconomicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEconomicsRequest) ProtoMessage() {}

func (x *GetEconomicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEconomicsRequest.ProtoReflect.Descriptor instead.
func (*GetEconomicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

type GetEconomicsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TokensSaved        int64                  `protobuf:"varint,1,opt,name=tokens_saved,json=tokensSaved,proto3" json:"tokens_saved,omitempty"`
	EstimatedCostSaved float64                `protobuf:"fixed64,2,opt,name=estimated_cost_saved,json=estimatedCostSaved,proto3" json:"estimated_cost_saved,omitempty"`
	ModelUsed          string                 `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	CostPerToken       float64                `protobuf:"fixed64,4,opt,name=cost_per_token,json=costPerToken,proto3" json:"cost_per_token,omitempty"`
	QuotaUsed          float64                `protobuf:"fixed64,5,opt,name=quota_used,json=quotaUsed,proto3" json:"quota_used,omitempty"`
	QuotaRemaining     float64                `protobuf:"fixed64,6,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetEconomicsResponse) Reset() {
	*x = GetEconomicsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEconomicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEconomicsResponse) ProtoMessage() {}

func (x *GetEconomicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEconomicsResponse.ProtoReflect.Descriptor instead.
func (*GetEconomicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetEconomicsResponse) GetTokensSaved() int64 {
	if x != nil {
		return x.TokensSaved
	}
	return 0
}

func (x *GetEconomicsResponse) GetEstimatedCostSaved() float64 {
	if x != nil {
		return x.EstimatedCostSaved
	}
	return 0
}

func (x *GetEconomicsResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *GetEconomicsResponse) GetCostPerToken() float64 {
	if x != nil {
		return x.CostPerToken
	}
	return 0
}

func (x *GetEconomicsResponse) GetQuotaUsed() float64 {
	if x != nil {
		return x.QuotaUsed
	}
	return 0
}

func (x *GetEconomicsResponse) GetQuotaRemaining() float64 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\x13tokman.analytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\rRecordRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12'\n" +
	"\x0foriginal_tokens\x18\x02 \x01(\x05R\x0eoriginalTokens\x12'\n" +
	"\x0ffiltered_tokens\x18\x03 \x01(\x05R\x0efilteredTokens\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vfilter_mode\x18\x06 \x01(\tR\n" +
	"filterMode\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"*\n" +
	"\x0eRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa4\x01\n" +
	"\x11GetMetricsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xf3\x02\n" +
	"\x12GetMetricsResponse\x12%\n" +
	"\x0etotal_commands\x18\x01 \x01(\x03R\rtotalCommands\x12,\n" +
	"\x12total_tokens_saved\x18\x02 \x01(\x03R\x10totalTokensSaved\x12&\n" +
	"\x0ftotal_tokens_in\x18\x03 \x01(\x03R\rtotalTokensIn\x12(\n" +
	"\x10total_tokens_out\x18\x04 \x01(\x03R\x0etotalTokensOut\x12'\n" +
	"\x0faverage_savings\x18\x05 \x01(\x01R\x0eaverageSavings\x12$\n" +
	"\x0ep50_latency_ms\x18\x06 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\a \x01(\x01R\fp99LatencyMs\x12A\n" +
	"\vtop_filters\x18\b \x03(\v2 .tokman.analytics.v1.FilterUsageR\n" +
	"topFilters\"e\n" +
	"\vFilterUsage\x12\x1f\n" +
	"\vfilter_name\x18\x01 \x01(\tR\n" +
	"filterName\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1f\n" +
	"\vavg_savings\x18\x03 \x01(\x01R\n" +
	"avgSavings\"\x15\n" +
	"\x13GetEconomicsRequest\"\xf8\x01\n" +
	"\x14GetEconomicsResponse\x12!\n" +
	"\ftokens_saved\x18\x01 \x01(\x03R\vtokensSaved\x120\n" +
	"\x14estimated_cost_saved\x18\x02 \x01(\x01R\x12estimatedCostSaved\x12\x1d\n" +
	"\n" +
	"model_used\x18\x03 \x01(\tR\tmodelUsed\x12$\n" +
	"\x0ecost_per_token\x18\x04 \x01(\x01R\fcostPerToken\x12\x1d\n" +
	"\n" +
	"quota_used\x18\x05 \x01(\x01R\tquotaUsed\x12'\n" +
	"\x0fquota_remaining\x18\x06 \x01(\x01R\x0equotaRemaining2\xa9\x02\n" +
	"\x10AnalyticsService\x12Q\n" +
	"\x06Record\x12\".tokman.analytics.v1.RecordRequest\x1a#.tokman.analytics.v1.RecordResponse\x12]\n" +
	"\n" +
	"GetMetrics\x12&.tokman.analytics.v1.GetMetricsRequest\x1a'.tokman.analytics.v1.GetMetricsResponse\x12c\n" +
	"\fGetEconomics\x12(.tokman.analytics.v1.GetEconomicsRequest\x1a).tokman.analytics.v1.GetEconomicsResponseB8Z6github.com/GrayCodeAI/tokman/pkg/api/proto/analyticsv1b\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_analytics_proto_goTypes = []any{
	(*RecordRequest)(nil),         // 0: tokman.analytics.v1.RecordRequest
	(*RecordResponse)(nil),        // 1: tokman.analytics.v1.RecordResponse
	(*GetMetricsRequest)(nil),     // 2: tokman.analytics.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),    // 3: tokman.analytics.v1.GetMetricsResponse
	(*FilterUsage)(nil),           // 4: tokman.analytics.v1.FilterUsage
	(*GetEconomicsRequest)(nil),   // 5: tokman.analytics.v1.GetEconomicsRequest
	(*GetEconomicsResponse)(nil),  // 6: tokman.analytics.v1.GetEconomicsResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_analytics_proto_depIdxs = []int32{
	7, // 0: tokman.analytics.v1.GetMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	7, // 1: tokman.analytics.v1.GetMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	4, // 2: tokman.analytics.v1.GetMetricsResponse.top_filters:type_name -> tokman.analytics.v1.FilterUsage
	0, // 3: tokman.analytics.v1.AnalyticsService.Record:input_type -> tokman.analytics.v1.RecordRequest
	2, // 4: tokman.analytics.v1.AnalyticsService.GetMetrics:input_type -> tokman.analytics.v1.GetMetricsRequest
	5, // 5: tokman.analytics.v1.AnalyticsService.GetEconomics:input_type -> tokman.analytics.v1.GetEconomicsRequest
	1, // 6: tokman.analytics.v1.AnalyticsService.Record:output_type -> tokman.analytics.v1.RecordResponse
	3, // 7: tokman.analytics.v1.AnalyticsService.GetMetrics:output_type -> tokman.analytics.v1.GetMetricsResponse
	6, // 8: tokman.analytics.v1.AnalyticsService.GetEconomics:output_type -> tokman.analytics.v1.GetEconomicsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
