package firewall

import "fmt"

type FirewallRule struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Direction string `json:"direction"`
	Protocol  string `json:"protocol"`
	Port      int    `json:"port"`
	Address   string `json:"address"`
	Action    string `json:"action"`
	Enabled   bool   `json:"enabled"`
}

type EgressFirewall struct {
	rules          []FirewallRule
	allowedDomains map[string]bool
	allowedIPs     map[string]bool
	dnsCache       map[string]string
}

func NewEgressFirewall() *EgressFirewall {
	return &EgressFirewall{
		allowedDomains: make(map[string]bool),
		allowedIPs:     make(map[string]bool),
		dnsCache:       make(map[string]string),
	}
}

func (f *EgressFirewall) AddAllowedDomain(domain string) {
	f.allowedDomains[domain] = true
}

func (f *EgressFirewall) AddAllowedIP(ip string) {
	f.allowedIPs[ip] = true
}

func (f *EgressFirewall) IsAllowed(domain, ip string) bool {
	if f.allowedDomains[domain] {
		return true
	}
	if f.allowedIPs[ip] {
		return true
	}
	return false
}

func (f *EgressFirewall) GenerateIptablesRules() []string {
	var rules []string
	rules = append(rules, "# TokMan Egress Firewall Rules")
	rules = append(rules, "# Generated by tokman")
	rules = append(rules, "")

	rules = append(rules, "# Default deny all egress")
	rules = append(rules, "iptables -A OUTPUT -j DROP")

	for domain := range f.allowedDomains {
		rules = append(rules, fmt.Sprintf("# Allow %s", domain))
		rules = append(rules, fmt.Sprintf("iptables -A OUTPUT -p tcp -d %s -j ACCEPT", domain))
	}

	for ip := range f.allowedIPs {
		rules = append(rules, fmt.Sprintf("# Allow %s", ip))
		rules = append(rules, fmt.Sprintf("iptables -A OUTPUT -p tcp -d %s -j ACCEPT", ip))
	}

	return rules
}

func (f *EgressFirewall) Status() map[string]interface{} {
	return map[string]interface{}{
		"allowed_domains": len(f.allowedDomains),
		"allowed_ips":     len(f.allowedIPs),
		"total_rules":     len(f.rules),
	}
}

func (f *EgressFirewall) AddRule(rule FirewallRule) {
	f.rules = append(f.rules, rule)
}

func (f *EgressFirewall) RemoveRule(id string) {
	for i, r := range f.rules {
		if r.ID == id {
			f.rules = append(f.rules[:i], f.rules[i+1:]...)
			return
		}
	}
}

func (f *EgressFirewall) Rollback() {
	f.rules = nil
}
