[tests]
[[tests.mix]]
name = "summarizes test"
input = """
Compiling 3 files (.ex)
Generated myapp app
....

Finished in 0.5 seconds
4 tests, 0 failures
"""
expected = "4 tests, 0 failures"

[[tests.mix]]
name = "shows test failures"
input = """
  1) test should validate input (MyAppTest)
     test/my_app_test.exs:10
     Assertion with == failed
     code:  assert validate(input) == :ok
     left:  :ok
     right: :error
     stacktrace:
       test/my_app_test.exs:12: (test)

Finished in 0.5 seconds
4 tests, 1 failure
"""
expected = """
FAILED: test should validate input
  test/my_app_test.exs:10

4 tests, 1 failure
"""
