[tests]
[[tests.watch]]
name = "summarizes watch"
input = "Every 2.0s: git status\n\nOn branch main                                                                  \nnothing to commit, working tree clean                                           "
expected = "nothing to commit, working tree clean"
