// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: proto/compression.proto

package compressionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompressionService_Compress_FullMethodName  = "/tokman.compression.v1.CompressionService/Compress"
	CompressionService_GetStats_FullMethodName  = "/tokman.compression.v1.CompressionService/GetStats"
	CompressionService_GetLayers_FullMethodName = "/tokman.compression.v1.CompressionService/GetLayers"
)

// CompressionServiceClient is the client API for CompressionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Compression service provides the 31-layer compression pipeline.
type CompressionServiceClient interface {
	// Compress applies the compression pipeline to input text.
	Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error)
	// GetStats returns compression statistics.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// GetLayers returns information about all compression layers.
	GetLayers(ctx context.Context, in *GetLayersRequest, opts ...grpc.CallOption) (*GetLayersResponse, error)
}

type compressionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompressionServiceClient(cc grpc.ClientConnInterface) CompressionServiceClient {
	return &compressionServiceClient{cc}
}

func (c *compressionServiceClient) Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompressResponse)
	err := c.cc.Invoke(ctx, CompressionService_Compress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compressionServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, CompressionService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compressionServiceClient) GetLayers(ctx context.Context, in *GetLayersRequest, opts ...grpc.CallOption) (*GetLayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLayersResponse)
	err := c.cc.Invoke(ctx, CompressionService_GetLayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompressionServiceServer is the server API for CompressionService service.
// All implementations must embed UnimplementedCompressionServiceServer
// for forward compatibility.
//
// Compression service provides the 31-layer compression pipeline.
type CompressionServiceServer interface {
	// Compress applies the compression pipeline to input text.
	Compress(context.Context, *CompressRequest) (*CompressResponse, error)
	// GetStats returns compression statistics.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// GetLayers returns information about all compression layers.
	GetLayers(context.Context, *GetLayersRequest) (*GetLayersResponse, error)
	mustEmbedUnimplementedCompressionServiceServer()
}

// UnimplementedCompressionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompressionServiceServer struct{}

func (UnimplementedCompressionServiceServer) Compress(context.Context, *CompressRequest) (*CompressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compress not implemented")
}
func (UnimplementedCompressionServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedCompressionServiceServer) GetLayers(context.Context, *GetLayersRequest) (*GetLayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLayers not implemented")
}
func (UnimplementedCompressionServiceServer) mustEmbedUnimplementedCompressionServiceServer() {}
func (UnimplementedCompressionServiceServer) testEmbeddedByValue()                            {}

// UnsafeCompressionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompressionServiceServer will
// result in compilation errors.
type UnsafeCompressionServiceServer interface {
	mustEmbedUnimplementedCompressionServiceServer()
}

func RegisterCompressionServiceServer(s grpc.ServiceRegistrar, srv CompressionServiceServer) {
	// If the following call panics, it indicates UnimplementedCompressionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompressionService_ServiceDesc, srv)
}

func _CompressionService_Compress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressionServiceServer).Compress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompressionService_Compress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressionServiceServer).Compress(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompressionService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressionServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompressionService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressionServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompressionService_GetLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressionServiceServer).GetLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompressionService_GetLayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressionServiceServer).GetLayers(ctx, req.(*GetLayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompressionService_ServiceDesc is the grpc.ServiceDesc for CompressionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompressionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokman.compression.v1.CompressionService",
	HandlerType: (*CompressionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compress",
			Handler:    _CompressionService_Compress_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _CompressionService_GetStats_Handler,
		},
		{
			MethodName: "GetLayers",
			Handler:    _CompressionService_GetLayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/compression.proto",
}
