// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/compression.proto

package compressionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // none, minimal, aggressive
	QueryIntent   string                 `protobuf:"bytes,3,opt,name=query_intent,json=queryIntent,proto3" json:"query_intent,omitempty"`
	Budget        int32                  `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`
	Preset        string                 `protobuf:"bytes,5,opt,name=preset,proto3" json:"preset,omitempty"` // fast, balanced, full
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressRequest) Reset() {
	*x = CompressRequest{}
	mi := &file_proto_compression_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressRequest) ProtoMessage() {}

func (x *CompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compression_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressRequest.ProtoReflect.Descriptor instead.
func (*CompressRequest) Descriptor() ([]byte, []int) {
	return file_proto_compression_proto_rawDescGZIP(), []int{0}
}

func (x *CompressRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *CompressRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CompressRequest) GetQueryIntent() string {
	if x != nil {
		return x.QueryIntent
	}
	return ""
}

func (x *CompressRequest) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *CompressRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

type CompressResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Output           string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	OriginalTokens   int32                  `protobuf:"varint,2,opt,name=original_tokens,json=originalTokens,proto3" json:"original_tokens,omitempty"`
	CompressedTokens int32                  `protobuf:"varint,3,opt,name=compressed_tokens,json=compressedTokens,proto3" json:"compressed_tokens,omitempty"`
	SavingsPercent   float64                `protobuf:"fixed64,4,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	LayersApplied    []string               `protobuf:"bytes,5,rep,name=layers_applied,json=layersApplied,proto3" json:"layers_applied,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompressResponse) Reset() {
	*x = CompressResponse{}
	mi := &file_proto_compression_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressResponse) ProtoMessage() {}

func (x *CompressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compression_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressResponse.ProtoReflect.Descriptor instead.
func (*CompressResponse) Descriptor() ([]byte, []int) {
	return file_proto_compression_proto_rawDescGZIP(), []int{1}
}

func (x *CompressResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CompressResponse) GetOriginalTokens() int32 {
	if x != nil {
		return x.OriginalTokens
	}
	return 0
}

func (x *CompressResponse) GetCompressedTokens() int32 {
	if x != nil {
		return x.CompressedTokens
	}
	return 0
}

func (x *CompressResponse) GetSavingsPercent() float64 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

func (x *CompressResponse) GetLayersApplied() []string {
	if x != nil {
		return x.LayersApplied
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_compression_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compression_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_compression_proto_rawDescGZIP(), []int{2}
}

type GetStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalCompressions  int64                  `protobuf:"varint,1,opt,name=total_compressions,json=totalCompressions,proto3" json:"total_compressions,omitempty"`
	TotalTokensSaved   int64                  `protobuf:"varint,2,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	AverageCompression float64                `protobuf:"fixed64,3,opt,name=average_compression,json=averageCompression,proto3" json:"average_compression,omitempty"`
	P99LatencyMs       float64                `protobuf:"fixed64,4,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_compression_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compression_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_compression_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatsResponse) GetTotalCompressions() int64 {
	if x != nil {
		return x.TotalCompressions
	}
	return 0
}

func (x *GetStatsResponse) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *GetStatsResponse) GetAverageCompression() float64 {
	if x != nil {
		return x.AverageCompression
	}
	return 0
}

func (x *GetStatsResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

type GetLayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLayersRequest) Reset() {
	*x = GetLayersRequest{}
	mi := &file_proto_compression_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLayersRequest) ProtoMessage() {}

func (x *GetLayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compression_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLayersRequest.ProtoReflect.Descriptor instead.
func (*GetLayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_compression_proto_rawDescGZIP(), []int{4}
}

type GetLayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layers        []*LayerInfo           `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLayersResponse) Reset() {
	*x = GetLayersResponse{}
	mi := &file_proto_compression_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLayersResponse) ProtoMessage() {}

func (x *GetLayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compression_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLayersResponse.ProtoReflect.Descriptor instead.
func (*GetLayersResponse) Descriptor() ([]byte, []int) {
	return file_proto_compression_proto_rawDescGZIP(), []int{5}
}

func (x *GetLayersResponse) GetLayers() []*LayerInfo {
	if x != nil {
		return x.Layers
	}
	return nil
}

type LayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Research      string                 `protobuf:"bytes,3,opt,name=research,proto3" json:"research,omitempty"`
	Compression   string                 `protobuf:"bytes,4,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerInfo) Reset() {
	*x = LayerInfo{}
	mi := &file_proto_compression_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerInfo) ProtoMessage() {}

func (x *LayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compression_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerInfo.ProtoReflect.Descriptor instead.
func (*LayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_compression_proto_rawDescGZIP(), []int{6}
}

func (x *LayerInfo) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *LayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LayerInfo) GetResearch() string {
	if x != nil {
		return x.Research
	}
	return ""
}

func (x *LayerInfo) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

var File_proto_compression_proto protoreflect.FileDescriptor

const file_proto_compression_proto_rawDesc = "" +
	"\n" +
	"\x17proto/compression.proto\x12\x15tokman.compression.v1\"\x8e\x01\n" +
	"\x0fCompressRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12!\n" +
	"\fquery_intent\x18\x03 \x01(\tR\vqueryIntent\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x05R\x06budget\x12\x16\n" +
	"\x06preset\x18\x05 \x01(\tR\x06preset\"\xd0\x01\n" +
	"\x10CompressResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12'\n" +
	"\x0foriginal_tokens\x18\x02 \x01(\x05R\x0eoriginalTokens\x12+\n" +
	"\x11compressed_tokens\x18\x03 \x01(\x05R\x10compressedTokens\x12'\n" +
	"\x0fsavings_percent\x18\x04 \x01(\x01R\x0esavingsPercent\x12%\n" +
	"\x0elayers_applied\x18\x05 \x03(\tR\rlayersApplied\"\x11\n" +
	"\x0fGetStatsRequest\"\xc6\x01\n" +
	"\x10GetStatsResponse\x12-\n" +
	"\x12total_compressions\x18\x01 \x01(\x03R\x11totalCompressions\x12,\n" +
	"\x12total_tokens_saved\x18\x02 \x01(\x03R\x10totalTokensSaved\x12/\n" +
	"\x13average_compression\x18\x03 \x01(\x01R\x12averageCompression\x12$\n" +
	"\x0ep99_latency_ms\x18\x04 \x01(\x01R\fp99LatencyMs\"\x12\n" +
	"\x10GetLayersRequest\"M\n" +
	"\x11GetLayersResponse\x128\n" +
	"\x06layers\x18\x01 \x03(\v2 .tokman.compression.v1.LayerInfoR\x06layers\"u\n" +
	"\tLayerInfo\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bresearch\x18\x03 \x01(\tR\bresearch\x12 \n" +
	"\vcompression\x18\x04 \x01(\tR\vcompression2\xae\x02\n" +
	"\x12CompressionService\x12[\n" +
	"\bCompress\x12&.tokman.compression.v1.CompressRequest\x1a'.tokman.compression.v1.CompressResponse\x12[\n" +
	"\bGetStats\x12&.tokman.compression.v1.GetStatsRequest\x1a'.tokman.compression.v1.GetStatsResponse\x12^\n" +
	"\tGetLayers\x12'.tokman.compression.v1.GetLayersRequest\x1a(.tokman.compression.v1.GetLayersResponseB:Z8github.com/GrayCodeAI/tokman/pkg/api/proto/compressionv1b\x06proto3"

var (
	file_proto_compression_proto_rawDescOnce sync.Once
	file_proto_compression_proto_rawDescData []byte
)

func file_proto_compression_proto_rawDescGZIP() []byte {
	file_proto_compression_proto_rawDescOnce.Do(func() {
		file_proto_compression_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compression_proto_rawDesc), len(file_proto_compression_proto_rawDesc)))
	})
	return file_proto_compression_proto_rawDescData
}

var file_proto_compression_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_compression_proto_goTypes = []any{
	(*CompressRequest)(nil),   // 0: tokman.compression.v1.CompressRequest
	(*CompressResponse)(nil),  // 1: tokman.compression.v1.CompressResponse
	(*GetStatsRequest)(nil),   // 2: tokman.compression.v1.GetStatsRequest
	(*GetStatsResponse)(nil),  // 3: tokman.compression.v1.GetStatsResponse
	(*GetLayersRequest)(nil),  // 4: tokman.compression.v1.GetLayersRequest
	(*GetLayersResponse)(nil), // 5: tokman.compression.v1.GetLayersResponse
	(*LayerInfo)(nil),         // 6: tokman.compression.v1.LayerInfo
}
var file_proto_compression_proto_depIdxs = []int32{
	6, // 0: tokman.compression.v1.GetLayersResponse.layers:type_name -> tokman.compression.v1.LayerInfo
	0, // 1: tokman.compression.v1.CompressionService.Compress:input_type -> tokman.compression.v1.CompressRequest
	2, // 2: tokman.compression.v1.CompressionService.GetStats:input_type -> tokman.compression.v1.GetStatsRequest
	4, // 3: tokman.compression.v1.CompressionService.GetLayers:input_type -> tokman.compression.v1.GetLayersRequest
	1, // 4: tokman.compression.v1.CompressionService.Compress:output_type -> tokman.compression.v1.CompressResponse
	3, // 5: tokman.compression.v1.CompressionService.GetStats:output_type -> tokman.compression.v1.GetStatsResponse
	5, // 6: tokman.compression.v1.CompressionService.GetLayers:output_type -> tokman.compression.v1.GetLayersResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_compression_proto_init() }
func file_proto_compression_proto_init() {
	if File_proto_compression_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compression_proto_rawDesc), len(file_proto_compression_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compression_proto_goTypes,
		DependencyIndexes: file_proto_compression_proto_depIdxs,
		MessageInfos:      file_proto_compression_proto_msgTypes,
	}.Build()
	File_proto_compression_proto = out.File
	file_proto_compression_proto_goTypes = nil
	file_proto_compression_proto_depIdxs = nil
}
