// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TeamId         string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	OriginalTokens int32                  `protobuf:"varint,4,opt,name=original_tokens,json=originalTokens,proto3" json:"original_tokens,omitempty"`
	FilteredTokens int32                  `protobuf:"varint,5,opt,name=filtered_tokens,json=filteredTokens,proto3" json:"filtered_tokens,omitempty"`
	DurationMs     int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ExitCode       int32                  `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	FilterMode     string                 `protobuf:"bytes,8,opt,name=filter_mode,json=filterMode,proto3" json:"filter_mode,omitempty"`
	SessionId      string                 `protobuf:"bytes,9,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentName      string                 `protobuf:"bytes,10,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ModelName      string                 `protobuf:"bytes,11,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Provider       string                 `protobuf:"bytes,12,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *RecordRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RecordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RecordRequest) GetOriginalTokens() int32 {
	if x != nil {
		return x.OriginalTokens
	}
	return 0
}

func (x *RecordRequest) GetFilteredTokens() int32 {
	if x != nil {
		return x.FilteredTokens
	}
	return 0
}

func (x *RecordRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecordRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RecordRequest) GetFilterMode() string {
	if x != nil {
		return x.FilterMode
	}
	return ""
}

func (x *RecordRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RecordRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RecordRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordId      int64                  `protobuf:"varint,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *RecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordResponse) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *RecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *GetMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetMetricsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMetricsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMetricsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalCommands         int64                  `protobuf:"varint,1,opt,name=total_commands,json=totalCommands,proto3" json:"total_commands,omitempty"`
	TotalTokensSaved      int64                  `protobuf:"varint,2,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	TotalTokensIn         int64                  `protobuf:"varint,3,opt,name=total_tokens_in,json=totalTokensIn,proto3" json:"total_tokens_in,omitempty"`
	TotalTokensOut        int64                  `protobuf:"varint,4,opt,name=total_tokens_out,json=totalTokensOut,proto3" json:"total_tokens_out,omitempty"`
	AverageSavingsPercent float64                `protobuf:"fixed64,5,opt,name=average_savings_percent,json=averageSavingsPercent,proto3" json:"average_savings_percent,omitempty"`
	P50LatencyMs          float64                `protobuf:"fixed64,6,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P99LatencyMs          float64                `protobuf:"fixed64,7,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	TopFilters            []*FilterUsage         `protobuf:"bytes,8,rep,name=top_filters,json=topFilters,proto3" json:"top_filters,omitempty"`
	EstimatedSavingsUsd   float64                `protobuf:"fixed64,9,opt,name=estimated_savings_usd,json=estimatedSavingsUsd,proto3" json:"estimated_savings_usd,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsResponse) GetTotalCommands() int64 {
	if x != nil {
		return x.TotalCommands
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTokensIn() int64 {
	if x != nil {
		return x.TotalTokensIn
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTokensOut() int64 {
	if x != nil {
		return x.TotalTokensOut
	}
	return 0
}

func (x *GetMetricsResponse) GetAverageSavingsPercent() float64 {
	if x != nil {
		return x.AverageSavingsPercent
	}
	return 0
}

func (x *GetMetricsResponse) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *GetMetricsResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *GetMetricsResponse) GetTopFilters() []*FilterUsage {
	if x != nil {
		return x.TopFilters
	}
	return nil
}

func (x *GetMetricsResponse) GetEstimatedSavingsUsd() float64 {
	if x != nil {
		return x.EstimatedSavingsUsd
	}
	return 0
}

type FilterUsage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FilterName         string                 `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	Count              int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AvgSavingsPercent  float64                `protobuf:"fixed64,3,opt,name=avg_savings_percent,json=avgSavingsPercent,proto3" json:"avg_savings_percent,omitempty"`
	TotalTokensSaved   int64                  `protobuf:"varint,4,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	EffectivenessScore float64                `protobuf:"fixed64,5,opt,name=effectiveness_score,json=effectivenessScore,proto3" json:"effectiveness_score,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FilterUsage) Reset() {
	*x = FilterUsage{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterUsage) ProtoMessage() {}

func (x *FilterUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterUsage.ProtoReflect.Descriptor instead.
func (*FilterUsage) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *FilterUsage) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *FilterUsage) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FilterUsage) GetAvgSavingsPercent() float64 {
	if x != nil {
		return x.AvgSavingsPercent
	}
	return 0
}

func (x *FilterUsage) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *FilterUsage) GetEffectivenessScore() float64 {
	if x != nil {
		return x.EffectivenessScore
	}
	return 0
}

type GetEconomicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEconomicsRequest) Reset() {
	*x = GetEconomicsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEconomicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEconomicsRequest) ProtoMessage() {}

func (x *GetEconomicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEconomicsRequest.ProtoReflect.Descriptor instead.
func (*GetEconomicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetEconomicsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *GetEconomicsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetEconomicsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetEconomicsResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	TokensSaved                int64                  `protobuf:"varint,1,opt,name=tokens_saved,json=tokensSaved,proto3" json:"tokens_saved,omitempty"`
	EstimatedCostSaved         float64                `protobuf:"fixed64,2,opt,name=estimated_cost_saved,json=estimatedCostSaved,proto3" json:"estimated_cost_saved,omitempty"`
	EstimatedCostWithoutTokman float64                `protobuf:"fixed64,3,opt,name=estimated_cost_without_tokman,json=estimatedCostWithoutTokman,proto3" json:"estimated_cost_without_tokman,omitempty"`
	RoiPercent                 float64                `protobuf:"fixed64,4,opt,name=roi_percent,json=roiPercent,proto3" json:"roi_percent,omitempty"`
	MonthlyCommands            int32                  `protobuf:"varint,5,opt,name=monthly_commands,json=monthlyCommands,proto3" json:"monthly_commands,omitempty"`
	AvgTokensPerCommand        float64                `protobuf:"fixed64,6,opt,name=avg_tokens_per_command,json=avgTokensPerCommand,proto3" json:"avg_tokens_per_command,omitempty"`
	PrimaryModel               string                 `protobuf:"bytes,7,opt,name=primary_model,json=primaryModel,proto3" json:"primary_model,omitempty"`
	CostPerMtok                float64                `protobuf:"fixed64,8,opt,name=cost_per_mtok,json=costPerMtok,proto3" json:"cost_per_mtok,omitempty"`
	QuotaUsedPercent           float64                `protobuf:"fixed64,9,opt,name=quota_used_percent,json=quotaUsedPercent,proto3" json:"quota_used_percent,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetEconomicsResponse) Reset() {
	*x = GetEconomicsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEconomicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEconomicsResponse) ProtoMessage() {}

func (x *GetEconomicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEconomicsResponse.ProtoReflect.Descriptor instead.
func (*GetEconomicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetEconomicsResponse) GetTokensSaved() int64 {
	if x != nil {
		return x.TokensSaved
	}
	return 0
}

func (x *GetEconomicsResponse) GetEstimatedCostSaved() float64 {
	if x != nil {
		return x.EstimatedCostSaved
	}
	return 0
}

func (x *GetEconomicsResponse) GetEstimatedCostWithoutTokman() float64 {
	if x != nil {
		return x.EstimatedCostWithoutTokman
	}
	return 0
}

func (x *GetEconomicsResponse) GetRoiPercent() float64 {
	if x != nil {
		return x.RoiPercent
	}
	return 0
}

func (x *GetEconomicsResponse) GetMonthlyCommands() int32 {
	if x != nil {
		return x.MonthlyCommands
	}
	return 0
}

func (x *GetEconomicsResponse) GetAvgTokensPerCommand() float64 {
	if x != nil {
		return x.AvgTokensPerCommand
	}
	return 0
}

func (x *GetEconomicsResponse) GetPrimaryModel() string {
	if x != nil {
		return x.PrimaryModel
	}
	return ""
}

func (x *GetEconomicsResponse) GetCostPerMtok() float64 {
	if x != nil {
		return x.CostPerMtok
	}
	return 0
}

func (x *GetEconomicsResponse) GetQuotaUsedPercent() float64 {
	if x != nil {
		return x.QuotaUsedPercent
	}
	return 0
}

type FilterEffectivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // "day", "week", "month"
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterEffectivenessRequest) Reset() {
	*x = FilterEffectivenessRequest{}
	mi := &file_proto_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterEffectivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterEffectivenessRequest) ProtoMessage() {}

func (x *FilterEffectivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterEffectivenessRequest.ProtoReflect.Descriptor instead.
func (*FilterEffectivenessRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *FilterEffectivenessRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *FilterEffectivenessRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *FilterEffectivenessRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FilterEffectivenessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*FilterMetric        `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterEffectivenessResponse) Reset() {
	*x = FilterEffectivenessResponse{}
	mi := &file_proto_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterEffectivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterEffectivenessResponse) ProtoMessage() {}

func (x *FilterEffectivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterEffectivenessResponse.ProtoReflect.Descriptor instead.
func (*FilterEffectivenessResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *FilterEffectivenessResponse) GetFilters() []*FilterMetric {
	if x != nil {
		return x.Filters
	}
	return nil
}

type FilterMetric struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FilterName          string                 `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	UsageCount          int64                  `protobuf:"varint,2,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	AvgEffectiveness    float64                `protobuf:"fixed64,3,opt,name=avg_effectiveness,json=avgEffectiveness,proto3" json:"avg_effectiveness,omitempty"`
	TotalTokensSaved    int64                  `protobuf:"varint,4,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	AvgProcessingTimeMs float64                `protobuf:"fixed64,5,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	FirstUsed           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=first_used,json=firstUsed,proto3" json:"first_used,omitempty"`
	LastUsed            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FilterMetric) Reset() {
	*x = FilterMetric{}
	mi := &file_proto_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterMetric) ProtoMessage() {}

func (x *FilterMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterMetric.ProtoReflect.Descriptor instead.
func (*FilterMetric) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *FilterMetric) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *FilterMetric) GetUsageCount() int64 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *FilterMetric) GetAvgEffectiveness() float64 {
	if x != nil {
		return x.AvgEffectiveness
	}
	return 0
}

func (x *FilterMetric) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *FilterMetric) GetAvgProcessingTimeMs() float64 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

func (x *FilterMetric) GetFirstUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstUsed
	}
	return nil
}

func (x *FilterMetric) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

type TrendAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Granularity   string                 `protobuf:"bytes,2,opt,name=granularity,proto3" json:"granularity,omitempty"` // "hourly", "daily", "weekly"
	Periods       int32                  `protobuf:"varint,3,opt,name=periods,proto3" json:"periods,omitempty"`        // number of periods to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendAnalysisRequest) Reset() {
	*x = TrendAnalysisRequest{}
	mi := &file_proto_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendAnalysisRequest) ProtoMessage() {}

func (x *TrendAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendAnalysisRequest.ProtoReflect.Descriptor instead.
func (*TrendAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *TrendAnalysisRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TrendAnalysisRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *TrendAnalysisRequest) GetPeriods() int32 {
	if x != nil {
		return x.Periods
	}
	return 0
}

type TrendAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TrendPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendAnalysisResponse) Reset() {
	*x = TrendAnalysisResponse{}
	mi := &file_proto_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendAnalysisResponse) ProtoMessage() {}

func (x *TrendAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendAnalysisResponse.ProtoReflect.Descriptor instead.
func (*TrendAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *TrendAnalysisResponse) GetPoints() []*TrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type TrendPoint struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalCommands       int64                  `protobuf:"varint,2,opt,name=total_commands,json=totalCommands,proto3" json:"total_commands,omitempty"`
	TotalOriginalTokens int64                  `protobuf:"varint,3,opt,name=total_original_tokens,json=totalOriginalTokens,proto3" json:"total_original_tokens,omitempty"`
	TotalFilteredTokens int64                  `protobuf:"varint,4,opt,name=total_filtered_tokens,json=totalFilteredTokens,proto3" json:"total_filtered_tokens,omitempty"`
	TotalSavedTokens    int64                  `protobuf:"varint,5,opt,name=total_saved_tokens,json=totalSavedTokens,proto3" json:"total_saved_tokens,omitempty"`
	AvgReductionPercent float64                `protobuf:"fixed64,6,opt,name=avg_reduction_percent,json=avgReductionPercent,proto3" json:"avg_reduction_percent,omitempty"`
	EstimatedCostUsd    float64                `protobuf:"fixed64,7,opt,name=estimated_cost_usd,json=estimatedCostUsd,proto3" json:"estimated_cost_usd,omitempty"`
	EstimatedSavingsUsd float64                `protobuf:"fixed64,8,opt,name=estimated_savings_usd,json=estimatedSavingsUsd,proto3" json:"estimated_savings_usd,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_proto_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *TrendPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TrendPoint) GetTotalCommands() int64 {
	if x != nil {
		return x.TotalCommands
	}
	return 0
}

func (x *TrendPoint) GetTotalOriginalTokens() int64 {
	if x != nil {
		return x.TotalOriginalTokens
	}
	return 0
}

func (x *TrendPoint) GetTotalFilteredTokens() int64 {
	if x != nil {
		return x.TotalFilteredTokens
	}
	return 0
}

func (x *TrendPoint) GetTotalSavedTokens() int64 {
	if x != nil {
		return x.TotalSavedTokens
	}
	return 0
}

func (x *TrendPoint) GetAvgReductionPercent() float64 {
	if x != nil {
		return x.AvgReductionPercent
	}
	return 0
}

func (x *TrendPoint) GetEstimatedCostUsd() float64 {
	if x != nil {
		return x.EstimatedCostUsd
	}
	return 0
}

func (x *TrendPoint) GetEstimatedSavingsUsd() float64 {
	if x != nil {
		return x.EstimatedSavingsUsd
	}
	return 0
}

type TeamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamStatsRequest) Reset() {
	*x = TeamStatsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStatsRequest) ProtoMessage() {}

func (x *TeamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStatsRequest.ProtoReflect.Descriptor instead.
func (*TeamStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *TeamStatsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type TeamStatsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TeamId               string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName             string                 `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	MemberCount          int32                  `protobuf:"varint,3,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	TotalCommands        int64                  `protobuf:"varint,4,opt,name=total_commands,json=totalCommands,proto3" json:"total_commands,omitempty"`
	TotalTokensSaved     int64                  `protobuf:"varint,5,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	AvgReductionPercent  float64                `protobuf:"fixed64,6,opt,name=avg_reduction_percent,json=avgReductionPercent,proto3" json:"avg_reduction_percent,omitempty"`
	MonthlyTokenBudget   int32                  `protobuf:"varint,7,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	TokensUsedThisMonth  int32                  `protobuf:"varint,8,opt,name=tokens_used_this_month,json=tokensUsedThisMonth,proto3" json:"tokens_used_this_month,omitempty"`
	EstimatedMonthlyCost float64                `protobuf:"fixed64,9,opt,name=estimated_monthly_cost,json=estimatedMonthlyCost,proto3" json:"estimated_monthly_cost,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TeamStatsResponse) Reset() {
	*x = TeamStatsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStatsResponse) ProtoMessage() {}

func (x *TeamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStatsResponse.ProtoReflect.Descriptor instead.
func (*TeamStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *TeamStatsResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamStatsResponse) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *TeamStatsResponse) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *TeamStatsResponse) GetTotalCommands() int64 {
	if x != nil {
		return x.TotalCommands
	}
	return 0
}

func (x *TeamStatsResponse) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *TeamStatsResponse) GetAvgReductionPercent() float64 {
	if x != nil {
		return x.AvgReductionPercent
	}
	return 0
}

func (x *TeamStatsResponse) GetMonthlyTokenBudget() int32 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

func (x *TeamStatsResponse) GetTokensUsedThisMonth() int32 {
	if x != nil {
		return x.TokensUsedThisMonth
	}
	return 0
}

func (x *TeamStatsResponse) GetEstimatedMonthlyCost() float64 {
	if x != nil {
		return x.EstimatedMonthlyCost
	}
	return 0
}

type UserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsRequest) Reset() {
	*x = UserStatsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsRequest) ProtoMessage() {}

func (x *UserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsRequest.ProtoReflect.Descriptor instead.
func (*UserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *UserStatsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email               string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	TotalCommands       int64                  `protobuf:"varint,3,opt,name=total_commands,json=totalCommands,proto3" json:"total_commands,omitempty"`
	TotalTokensSaved    int64                  `protobuf:"varint,4,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	AvgReductionPercent float64                `protobuf:"fixed64,5,opt,name=avg_reduction_percent,json=avgReductionPercent,proto3" json:"avg_reduction_percent,omitempty"`
	LastCommand         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_command,json=lastCommand,proto3" json:"last_command,omitempty"`
	MostUsedFilter      string                 `protobuf:"bytes,7,opt,name=most_used_filter,json=mostUsedFilter,proto3" json:"most_used_filter,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *UserStatsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStatsResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserStatsResponse) GetTotalCommands() int64 {
	if x != nil {
		return x.TotalCommands
	}
	return 0
}

func (x *UserStatsResponse) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *UserStatsResponse) GetAvgReductionPercent() float64 {
	if x != nil {
		return x.AvgReductionPercent
	}
	return 0
}

func (x *UserStatsResponse) GetLastCommand() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCommand
	}
	return nil
}

func (x *UserStatsResponse) GetMostUsedFilter() string {
	if x != nil {
		return x.MostUsedFilter
	}
	return ""
}

type CostProjectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DaysToProject int32                  `protobuf:"varint,2,opt,name=days_to_project,json=daysToProject,proto3" json:"days_to_project,omitempty"` // project this many days ahead
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostProjectionRequest) Reset() {
	*x = CostProjectionRequest{}
	mi := &file_proto_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostProjectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostProjectionRequest) ProtoMessage() {}

func (x *CostProjectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostProjectionRequest.ProtoReflect.Descriptor instead.
func (*CostProjectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *CostProjectionRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CostProjectionRequest) GetDaysToProject() int32 {
	if x != nil {
		return x.DaysToProject
	}
	return 0
}

type CostProjectionResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ProjectedMonthlyCost    float64                `protobuf:"fixed64,1,opt,name=projected_monthly_cost,json=projectedMonthlyCost,proto3" json:"projected_monthly_cost,omitempty"`
	ProjectedMonthlySavings float64                `protobuf:"fixed64,2,opt,name=projected_monthly_savings,json=projectedMonthlySavings,proto3" json:"projected_monthly_savings,omitempty"`
	ActualMonthlyCost       float64                `protobuf:"fixed64,3,opt,name=actual_monthly_cost,json=actualMonthlyCost,proto3" json:"actual_monthly_cost,omitempty"`
	ActualMonthlySavings    float64                `protobuf:"fixed64,4,opt,name=actual_monthly_savings,json=actualMonthlySavings,proto3" json:"actual_monthly_savings,omitempty"`
	ProjectionBasis         string                 `protobuf:"bytes,5,opt,name=projection_basis,json=projectionBasis,proto3" json:"projection_basis,omitempty"` // "last_7_days", "last_30_days", etc.
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CostProjectionResponse) Reset() {
	*x = CostProjectionResponse{}
	mi := &file_proto_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostProjectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostProjectionResponse) ProtoMessage() {}

func (x *CostProjectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostProjectionResponse.ProtoReflect.Descriptor instead.
func (*CostProjectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *CostProjectionResponse) GetProjectedMonthlyCost() float64 {
	if x != nil {
		return x.ProjectedMonthlyCost
	}
	return 0
}

func (x *CostProjectionResponse) GetProjectedMonthlySavings() float64 {
	if x != nil {
		return x.ProjectedMonthlySavings
	}
	return 0
}

func (x *CostProjectionResponse) GetActualMonthlyCost() float64 {
	if x != nil {
		return x.ActualMonthlyCost
	}
	return 0
}

func (x *CostProjectionResponse) GetActualMonthlySavings() float64 {
	if x != nil {
		return x.ActualMonthlySavings
	}
	return 0
}

func (x *CostProjectionResponse) GetProjectionBasis() string {
	if x != nil {
		return x.ProjectionBasis
	}
	return ""
}

type AuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ActionFilter  string                 `protobuf:"bytes,4,opt,name=action_filter,json=actionFilter,proto3" json:"action_filter,omitempty"` // filter by action type
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogsRequest) Reset() {
	*x = AuditLogsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogsRequest) ProtoMessage() {}

func (x *AuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogsRequest.ProtoReflect.Descriptor instead.
func (*AuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *AuditLogsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AuditLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AuditLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *AuditLogsRequest) GetActionFilter() string {
	if x != nil {
		return x.ActionFilter
	}
	return ""
}

func (x *AuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AuditLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLogEntry       `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogsResponse) Reset() {
	*x = AuditLogsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogsResponse) ProtoMessage() {}

func (x *AuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogsResponse.ProtoReflect.Descriptor instead.
func (*AuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *AuditLogsResponse) GetLogs() []*AuditLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AuditLogsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	OldValue      string                 `protobuf:"bytes,6,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      string                 `protobuf:"bytes,7,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IpAddress     string                 `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_proto_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *AuditLogEntry) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *AuditLogEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLogEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogEntry) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditLogEntry) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditLogEntry) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *AuditLogEntry) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *AuditLogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditLogEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type CreateTeamRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug               string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MonthlyTokenBudget int32                  `protobuf:"varint,4,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_proto_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTeamRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTeamRequest) GetMonthlyTokenBudget() int32 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_proto_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *GetTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type TeamResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TeamId             string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug               string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MonthlyTokenBudget int32                  `protobuf:"varint,5,opt,name=monthly_token_budget,json=monthlyTokenBudget,proto3" json:"monthly_token_budget,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TeamResponse) Reset() {
	*x = TeamResponse{}
	mi := &file_proto_analytics_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamResponse) ProtoMessage() {}

func (x *TeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamResponse.ProtoReflect.Descriptor instead.
func (*TeamResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{24}
}

func (x *TeamResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TeamResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TeamResponse) GetMonthlyTokenBudget() int32 {
	if x != nil {
		return x.MonthlyTokenBudget
	}
	return 0
}

func (x *TeamResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TeamResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateTeamBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	NewBudget     int32                  `protobuf:"varint,2,opt,name=new_budget,json=newBudget,proto3" json:"new_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamBudgetRequest) Reset() {
	*x = UpdateTeamBudgetRequest{}
	mi := &file_proto_analytics_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamBudgetRequest) ProtoMessage() {}

func (x *UpdateTeamBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamBudgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamBudgetRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateTeamBudgetRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateTeamBudgetRequest) GetNewBudget() int32 {
	if x != nil {
		return x.NewBudget
	}
	return 0
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RoleFilter    string                 `protobuf:"bytes,2,opt,name=role_filter,json=roleFilter,proto3" json:"role_filter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_analytics_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{26}
}

func (x *ListUsersRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListUsersRequest) GetRoleFilter() string {
	if x != nil {
		return x.RoleFilter
	}
	return ""
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_analytics_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{27}
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "admin", "editor", "viewer"
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_analytics_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{28}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserInfo) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardRequest) Reset() {
	*x = DashboardRequest{}
	mi := &file_proto_analytics_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRequest) ProtoMessage() {}

func (x *DashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRequest.ProtoReflect.Descriptor instead.
func (*DashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{29}
}

func (x *DashboardRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *DashboardRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *DashboardRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type DashboardResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TeamStats     *TeamStats              `protobuf:"bytes,1,opt,name=team_stats,json=teamStats,proto3" json:"team_stats,omitempty"`
	Economics     *GetEconomicsResponse   `protobuf:"bytes,2,opt,name=economics,proto3" json:"economics,omitempty"`
	Trends        []*TrendPoint           `protobuf:"bytes,3,rep,name=trends,proto3" json:"trends,omitempty"`
	TopFilters    []*FilterMetric         `protobuf:"bytes,4,rep,name=top_filters,json=topFilters,proto3" json:"top_filters,omitempty"`
	UserStats     []*UserStats            `protobuf:"bytes,5,rep,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	Projection    *CostProjectionResponse `protobuf:"bytes,6,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_proto_analytics_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{30}
}

func (x *DashboardResponse) GetTeamStats() *TeamStats {
	if x != nil {
		return x.TeamStats
	}
	return nil
}

func (x *DashboardResponse) GetEconomics() *GetEconomicsResponse {
	if x != nil {
		return x.Economics
	}
	return nil
}

func (x *DashboardResponse) GetTrends() []*TrendPoint {
	if x != nil {
		return x.Trends
	}
	return nil
}

func (x *DashboardResponse) GetTopFilters() []*FilterMetric {
	if x != nil {
		return x.TopFilters
	}
	return nil
}

func (x *DashboardResponse) GetUserStats() []*UserStats {
	if x != nil {
		return x.UserStats
	}
	return nil
}

func (x *DashboardResponse) GetProjection() *CostProjectionResponse {
	if x != nil {
		return x.Projection
	}
	return nil
}

type TeamStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalCommands        int64                  `protobuf:"varint,1,opt,name=total_commands,json=totalCommands,proto3" json:"total_commands,omitempty"`
	TotalTokensSaved     int64                  `protobuf:"varint,2,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	AvgReductionPercent  float64                `protobuf:"fixed64,3,opt,name=avg_reduction_percent,json=avgReductionPercent,proto3" json:"avg_reduction_percent,omitempty"`
	MemberCount          int32                  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	EstimatedMonthlyCost float64                `protobuf:"fixed64,5,opt,name=estimated_monthly_cost,json=estimatedMonthlyCost,proto3" json:"estimated_monthly_cost,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TeamStats) Reset() {
	*x = TeamStats{}
	mi := &file_proto_analytics_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStats) ProtoMessage() {}

func (x *TeamStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStats.ProtoReflect.Descriptor instead.
func (*TeamStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{31}
}

func (x *TeamStats) GetTotalCommands() int64 {
	if x != nil {
		return x.TotalCommands
	}
	return 0
}

func (x *TeamStats) GetTotalTokensSaved() int64 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *TeamStats) GetAvgReductionPercent() float64 {
	if x != nil {
		return x.AvgReductionPercent
	}
	return 0
}

func (x *TeamStats) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *TeamStats) GetEstimatedMonthlyCost() float64 {
	if x != nil {
		return x.EstimatedMonthlyCost
	}
	return 0
}

type UserStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CommandsToday    int64                  `protobuf:"varint,3,opt,name=commands_today,json=commandsToday,proto3" json:"commands_today,omitempty"`
	TokensSavedToday int64                  `protobuf:"varint,4,opt,name=tokens_saved_today,json=tokensSavedToday,proto3" json:"tokens_saved_today,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_proto_analytics_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{32}
}

func (x *UserStats) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStats) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserStats) GetCommandsToday() int64 {
	if x != nil {
		return x.CommandsToday
	}
	return 0
}

func (x *UserStats) GetTokensSavedToday() int64 {
	if x != nil {
		return x.TokensSavedToday
	}
	return 0
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\x13tokman.analytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\rRecordRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12'\n" +
	"\x0foriginal_tokens\x18\x04 \x01(\x05R\x0eoriginalTokens\x12'\n" +
	"\x0ffiltered_tokens\x18\x05 \x01(\x05R\x0efilteredTokens\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vfilter_mode\x18\b \x01(\tR\n" +
	"filterMode\x12\x1d\n" +
	"\n" +
	"session_id\x18\t \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\n" +
	" \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"model_name\x18\v \x01(\tR\tmodelName\x12\x1a\n" +
	"\bprovider\x18\f \x01(\tR\bprovider\"a\n" +
	"\x0eRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\x03R\brecordId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd6\x01\n" +
	"\x11GetMetricsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"\xb6\x03\n" +
	"\x12GetMetricsResponse\x12%\n" +
	"\x0etotal_commands\x18\x01 \x01(\x03R\rtotalCommands\x12,\n" +
	"\x12total_tokens_saved\x18\x02 \x01(\x03R\x10totalTokensSaved\x12&\n" +
	"\x0ftotal_tokens_in\x18\x03 \x01(\x03R\rtotalTokensIn\x12(\n" +
	"\x10total_tokens_out\x18\x04 \x01(\x03R\x0etotalTokensOut\x126\n" +
	"\x17average_savings_percent\x18\x05 \x01(\x01R\x15averageSavingsPercent\x12$\n" +
	"\x0ep50_latency_ms\x18\x06 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\a \x01(\x01R\fp99LatencyMs\x12A\n" +
	"\vtop_filters\x18\b \x03(\v2 .tokman.analytics.v1.FilterUsageR\n" +
	"topFilters\x122\n" +
	"\x15estimated_savings_usd\x18\t \x01(\x01R\x13estimatedSavingsUsd\"\xd3\x01\n" +
	"\vFilterUsage\x12\x1f\n" +
	"\vfilter_name\x18\x01 \x01(\tR\n" +
	"filterName\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12.\n" +
	"\x13avg_savings_percent\x18\x03 \x01(\x01R\x11avgSavingsPercent\x12,\n" +
	"\x12total_tokens_saved\x18\x04 \x01(\x03R\x10totalTokensSaved\x12/\n" +
	"\x13effectiveness_score\x18\x05 \x01(\x01R\x12effectivenessScore\"\xa0\x01\n" +
	"\x13GetEconomicsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xa6\x03\n" +
	"\x14GetEconomicsResponse\x12!\n" +
	"\ftokens_saved\x18\x01 \x01(\x03R\vtokensSaved\x120\n" +
	"\x14estimated_cost_saved\x18\x02 \x01(\x01R\x12estimatedCostSaved\x12A\n" +
	"\x1destimated_cost_without_tokman\x18\x03 \x01(\x01R\x1aestimatedCostWithoutTokman\x12\x1f\n" +
	"\vroi_percent\x18\x04 \x01(\x01R\n" +
	"roiPercent\x12)\n" +
	"\x10monthly_commands\x18\x05 \x01(\x05R\x0fmonthlyCommands\x123\n" +
	"\x16avg_tokens_per_command\x18\x06 \x01(\x01R\x13avgTokensPerCommand\x12#\n" +
	"\rprimary_model\x18\a \x01(\tR\fprimaryModel\x12\"\n" +
	"\rcost_per_mtok\x18\b \x01(\x01R\vcostPerMtok\x12,\n" +
	"\x12quota_used_percent\x18\t \x01(\x01R\x10quotaUsedPercent\"c\n" +
	"\x1aFilterEffectivenessRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"Z\n" +
	"\x1bFilterEffectivenessResponse\x12;\n" +
	"\afilters\x18\x01 \x03(\v2!.tokman.analytics.v1.FilterMetricR\afilters\"\xd4\x02\n" +
	"\fFilterMetric\x12\x1f\n" +
	"\vfilter_name\x18\x01 \x01(\tR\n" +
	"filterName\x12\x1f\n" +
	"\vusage_count\x18\x02 \x01(\x03R\n" +
	"usageCount\x12+\n" +
	"\x11avg_effectiveness\x18\x03 \x01(\x01R\x10avgEffectiveness\x12,\n" +
	"\x12total_tokens_saved\x18\x04 \x01(\x03R\x10totalTokensSaved\x123\n" +
	"\x16avg_processing_time_ms\x18\x05 \x01(\x01R\x13avgProcessingTimeMs\x129\n" +
	"\n" +
	"first_used\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstUsed\x127\n" +
	"\tlast_used\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\"k\n" +
	"\x14TrendAnalysisRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12 \n" +
	"\vgranularity\x18\x02 \x01(\tR\vgranularity\x12\x18\n" +
	"\aperiods\x18\x03 \x01(\x05R\aperiods\"P\n" +
	"\x15TrendAnalysisResponse\x127\n" +
	"\x06points\x18\x01 \x03(\v2\x1f.tokman.analytics.v1.TrendPointR\x06points\"\x99\x03\n" +
	"\n" +
	"TrendPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0etotal_commands\x18\x02 \x01(\x03R\rtotalCommands\x122\n" +
	"\x15total_original_tokens\x18\x03 \x01(\x03R\x13totalOriginalTokens\x122\n" +
	"\x15total_filtered_tokens\x18\x04 \x01(\x03R\x13totalFilteredTokens\x12,\n" +
	"\x12total_saved_tokens\x18\x05 \x01(\x03R\x10totalSavedTokens\x122\n" +
	"\x15avg_reduction_percent\x18\x06 \x01(\x01R\x13avgReductionPercent\x12,\n" +
	"\x12estimated_cost_usd\x18\a \x01(\x01R\x10estimatedCostUsd\x122\n" +
	"\x15estimated_savings_usd\x18\b \x01(\x01R\x13estimatedSavingsUsd\"+\n" +
	"\x10TeamStatsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\x92\x03\n" +
	"\x11TeamStatsResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1b\n" +
	"\tteam_name\x18\x02 \x01(\tR\bteamName\x12!\n" +
	"\fmember_count\x18\x03 \x01(\x05R\vmemberCount\x12%\n" +
	"\x0etotal_commands\x18\x04 \x01(\x03R\rtotalCommands\x12,\n" +
	"\x12total_tokens_saved\x18\x05 \x01(\x03R\x10totalTokensSaved\x122\n" +
	"\x15avg_reduction_percent\x18\x06 \x01(\x01R\x13avgReductionPercent\x120\n" +
	"\x14monthly_token_budget\x18\a \x01(\x05R\x12monthlyTokenBudget\x123\n" +
	"\x16tokens_used_this_month\x18\b \x01(\x05R\x13tokensUsedThisMonth\x124\n" +
	"\x16estimated_monthly_cost\x18\t \x01(\x01R\x14estimatedMonthlyCost\"D\n" +
	"\x10UserStatsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xb4\x02\n" +
	"\x11UserStatsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0etotal_commands\x18\x03 \x01(\x03R\rtotalCommands\x12,\n" +
	"\x12total_tokens_saved\x18\x04 \x01(\x03R\x10totalTokensSaved\x122\n" +
	"\x15avg_reduction_percent\x18\x05 \x01(\x01R\x13avgReductionPercent\x12=\n" +
	"\flast_command\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastCommand\x12(\n" +
	"\x10most_used_filter\x18\a \x01(\tR\x0emostUsedFilter\"X\n" +
	"\x15CostProjectionRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12&\n" +
	"\x0fdays_to_project\x18\x02 \x01(\x05R\rdaysToProject\"\x9b\x02\n" +
	"\x16CostProjectionResponse\x124\n" +
	"\x16projected_monthly_cost\x18\x01 \x01(\x01R\x14projectedMonthlyCost\x12:\n" +
	"\x19projected_monthly_savings\x18\x02 \x01(\x01R\x17projectedMonthlySavings\x12.\n" +
	"\x13actual_monthly_cost\x18\x03 \x01(\x01R\x11actualMonthlyCost\x124\n" +
	"\x16actual_monthly_savings\x18\x04 \x01(\x01R\x14actualMonthlySavings\x12)\n" +
	"\x10projection_basis\x18\x05 \x01(\tR\x0fprojectionBasis\"\xf0\x01\n" +
	"\x10AuditLogsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\raction_filter\x18\x04 \x01(\tR\factionFilter\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"l\n" +
	"\x11AuditLogsResponse\x126\n" +
	"\x04logs\x18\x01 \x03(\v2\".tokman.analytics.v1.AuditLogEntryR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xb1\x02\n" +
	"\rAuditLogEntry\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\told_value\x18\x06 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\a \x01(\tR\bnewValue\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\"\x8f\x01\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x14monthly_token_budget\x18\x04 \x01(\x05R\x12monthlyTokenBudget\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\x99\x02\n" +
	"\fTeamResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x120\n" +
	"\x14monthly_token_budget\x18\x05 \x01(\x05R\x12monthlyTokenBudget\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Q\n" +
	"\x17UpdateTeamBudgetRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"new_budget\x18\x02 \x01(\x05R\tnewBudget\"z\n" +
	"\x10ListUsersRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1f\n" +
	"\vrole_filter\x18\x02 \x01(\tR\n" +
	"roleFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"i\n" +
	"\x11ListUsersResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.tokman.analytics.v1.UserInfoR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xfd\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"last_login\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9d\x01\n" +
	"\x10DashboardRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xa4\x03\n" +
	"\x11DashboardResponse\x12=\n" +
	"\n" +
	"team_stats\x18\x01 \x01(\v2\x1e.tokman.analytics.v1.TeamStatsR\tteamStats\x12G\n" +
	"\teconomics\x18\x02 \x01(\v2).tokman.analytics.v1.GetEconomicsResponseR\teconomics\x127\n" +
	"\x06trends\x18\x03 \x03(\v2\x1f.tokman.analytics.v1.TrendPointR\x06trends\x12B\n" +
	"\vtop_filters\x18\x04 \x03(\v2!.tokman.analytics.v1.FilterMetricR\n" +
	"topFilters\x12=\n" +
	"\n" +
	"user_stats\x18\x05 \x03(\v2\x1e.tokman.analytics.v1.UserStatsR\tuserStats\x12K\n" +
	"\n" +
	"projection\x18\x06 \x01(\v2+.tokman.analytics.v1.CostProjectionResponseR\n" +
	"projection\"\xed\x01\n" +
	"\tTeamStats\x12%\n" +
	"\x0etotal_commands\x18\x01 \x01(\x03R\rtotalCommands\x12,\n" +
	"\x12total_tokens_saved\x18\x02 \x01(\x03R\x10totalTokensSaved\x122\n" +
	"\x15avg_reduction_percent\x18\x03 \x01(\x01R\x13avgReductionPercent\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x05R\vmemberCount\x124\n" +
	"\x16estimated_monthly_cost\x18\x05 \x01(\x01R\x14estimatedMonthlyCost\"\x8f\x01\n" +
	"\tUserStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0ecommands_today\x18\x03 \x01(\x03R\rcommandsToday\x12,\n" +
	"\x12tokens_saved_today\x18\x04 \x01(\x03R\x10tokensSavedToday2\xec\n" +
	"\n" +
	"\x10AnalyticsService\x12Q\n" +
	"\x06Record\x12\".tokman.analytics.v1.RecordRequest\x1a#.tokman.analytics.v1.RecordResponse\x12]\n" +
	"\n" +
	"GetMetrics\x12&.tokman.analytics.v1.GetMetricsRequest\x1a'.tokman.analytics.v1.GetMetricsResponse\x12c\n" +
	"\fGetEconomics\x12(.tokman.analytics.v1.GetEconomicsRequest\x1a).tokman.analytics.v1.GetEconomicsResponse\x12{\n" +
	"\x16GetFilterEffectiveness\x12/.tokman.analytics.v1.FilterEffectivenessRequest\x1a0.tokman.analytics.v1.FilterEffectivenessResponse\x12i\n" +
	"\x10GetTrendAnalysis\x12).tokman.analytics.v1.TrendAnalysisRequest\x1a*.tokman.analytics.v1.TrendAnalysisResponse\x12]\n" +
	"\fGetTeamStats\x12%.tokman.analytics.v1.TeamStatsRequest\x1a&.tokman.analytics.v1.TeamStatsResponse\x12]\n" +
	"\fGetUserStats\x12%.tokman.analytics.v1.UserStatsRequest\x1a&.tokman.analytics.v1.UserStatsResponse\x12l\n" +
	"\x11GetCostProjection\x12*.tokman.analytics.v1.CostProjectionRequest\x1a+.tokman.analytics.v1.CostProjectionResponse\x12]\n" +
	"\fGetAuditLogs\x12%.tokman.analytics.v1.AuditLogsRequest\x1a&.tokman.analytics.v1.AuditLogsResponse\x12W\n" +
	"\n" +
	"CreateTeam\x12&.tokman.analytics.v1.CreateTeamRequest\x1a!.tokman.analytics.v1.TeamResponse\x12Q\n" +
	"\aGetTeam\x12#.tokman.analytics.v1.GetTeamRequest\x1a!.tokman.analytics.v1.TeamResponse\x12c\n" +
	"\x10UpdateTeamBudget\x12,.tokman.analytics.v1.UpdateTeamBudgetRequest\x1a!.tokman.analytics.v1.TeamResponse\x12Z\n" +
	"\tListUsers\x12%.tokman.analytics.v1.ListUsersRequest\x1a&.tokman.analytics.v1.ListUsersResponse\x12a\n" +
	"\x10GetDashboardData\x12%.tokman.analytics.v1.DashboardRequest\x1a&.tokman.analytics.v1.DashboardResponseB8Z6github.com/GrayCodeAI/tokman/pkg/api/proto/analyticsv1b\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_analytics_proto_goTypes = []any{
	(*RecordRequest)(nil),               // 0: tokman.analytics.v1.RecordRequest
	(*RecordResponse)(nil),              // 1: tokman.analytics.v1.RecordResponse
	(*GetMetricsRequest)(nil),           // 2: tokman.analytics.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),          // 3: tokman.analytics.v1.GetMetricsResponse
	(*FilterUsage)(nil),                 // 4: tokman.analytics.v1.FilterUsage
	(*GetEconomicsRequest)(nil),         // 5: tokman.analytics.v1.GetEconomicsRequest
	(*GetEconomicsResponse)(nil),        // 6: tokman.analytics.v1.GetEconomicsResponse
	(*FilterEffectivenessRequest)(nil),  // 7: tokman.analytics.v1.FilterEffectivenessRequest
	(*FilterEffectivenessResponse)(nil), // 8: tokman.analytics.v1.FilterEffectivenessResponse
	(*FilterMetric)(nil),                // 9: tokman.analytics.v1.FilterMetric
	(*TrendAnalysisRequest)(nil),        // 10: tokman.analytics.v1.TrendAnalysisRequest
	(*TrendAnalysisResponse)(nil),       // 11: tokman.analytics.v1.TrendAnalysisResponse
	(*TrendPoint)(nil),                  // 12: tokman.analytics.v1.TrendPoint
	(*TeamStatsRequest)(nil),            // 13: tokman.analytics.v1.TeamStatsRequest
	(*TeamStatsResponse)(nil),           // 14: tokman.analytics.v1.TeamStatsResponse
	(*UserStatsRequest)(nil),            // 15: tokman.analytics.v1.UserStatsRequest
	(*UserStatsResponse)(nil),           // 16: tokman.analytics.v1.UserStatsResponse
	(*CostProjectionRequest)(nil),       // 17: tokman.analytics.v1.CostProjectionRequest
	(*CostProjectionResponse)(nil),      // 18: tokman.analytics.v1.CostProjectionResponse
	(*AuditLogsRequest)(nil),            // 19: tokman.analytics.v1.AuditLogsRequest
	(*AuditLogsResponse)(nil),           // 20: tokman.analytics.v1.AuditLogsResponse
	(*AuditLogEntry)(nil),               // 21: tokman.analytics.v1.AuditLogEntry
	(*CreateTeamRequest)(nil),           // 22: tokman.analytics.v1.CreateTeamRequest
	(*GetTeamRequest)(nil),              // 23: tokman.analytics.v1.GetTeamRequest
	(*TeamResponse)(nil),                // 24: tokman.analytics.v1.TeamResponse
	(*UpdateTeamBudgetRequest)(nil),     // 25: tokman.analytics.v1.UpdateTeamBudgetRequest
	(*ListUsersRequest)(nil),            // 26: tokman.analytics.v1.ListUsersRequest
	(*ListUsersResponse)(nil),           // 27: tokman.analytics.v1.ListUsersResponse
	(*UserInfo)(nil),                    // 28: tokman.analytics.v1.UserInfo
	(*DashboardRequest)(nil),            // 29: tokman.analytics.v1.DashboardRequest
	(*DashboardResponse)(nil),           // 30: tokman.analytics.v1.DashboardResponse
	(*TeamStats)(nil),                   // 31: tokman.analytics.v1.TeamStats
	(*UserStats)(nil),                   // 32: tokman.analytics.v1.UserStats
	(*timestamppb.Timestamp)(nil),       // 33: google.protobuf.Timestamp
}
var file_proto_analytics_proto_depIdxs = []int32{
	33, // 0: tokman.analytics.v1.GetMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	33, // 1: tokman.analytics.v1.GetMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	4,  // 2: tokman.analytics.v1.GetMetricsResponse.top_filters:type_name -> tokman.analytics.v1.FilterUsage
	33, // 3: tokman.analytics.v1.GetEconomicsRequest.start_time:type_name -> google.protobuf.Timestamp
	33, // 4: tokman.analytics.v1.GetEconomicsRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 5: tokman.analytics.v1.FilterEffectivenessResponse.filters:type_name -> tokman.analytics.v1.FilterMetric
	33, // 6: tokman.analytics.v1.FilterMetric.first_used:type_name -> google.protobuf.Timestamp
	33, // 7: tokman.analytics.v1.FilterMetric.last_used:type_name -> google.protobuf.Timestamp
	12, // 8: tokman.analytics.v1.TrendAnalysisResponse.points:type_name -> tokman.analytics.v1.TrendPoint
	33, // 9: tokman.analytics.v1.TrendPoint.timestamp:type_name -> google.protobuf.Timestamp
	33, // 10: tokman.analytics.v1.UserStatsResponse.last_command:type_name -> google.protobuf.Timestamp
	33, // 11: tokman.analytics.v1.AuditLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	33, // 12: tokman.analytics.v1.AuditLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	21, // 13: tokman.analytics.v1.AuditLogsResponse.logs:type_name -> tokman.analytics.v1.AuditLogEntry
	33, // 14: tokman.analytics.v1.AuditLogEntry.created_at:type_name -> google.protobuf.Timestamp
	33, // 15: tokman.analytics.v1.TeamResponse.created_at:type_name -> google.protobuf.Timestamp
	33, // 16: tokman.analytics.v1.TeamResponse.updated_at:type_name -> google.protobuf.Timestamp
	28, // 17: tokman.analytics.v1.ListUsersResponse.users:type_name -> tokman.analytics.v1.UserInfo
	33, // 18: tokman.analytics.v1.UserInfo.last_login:type_name -> google.protobuf.Timestamp
	33, // 19: tokman.analytics.v1.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	33, // 20: tokman.analytics.v1.DashboardRequest.start_time:type_name -> google.protobuf.Timestamp
	33, // 21: tokman.analytics.v1.DashboardRequest.end_time:type_name -> google.protobuf.Timestamp
	31, // 22: tokman.analytics.v1.DashboardResponse.team_stats:type_name -> tokman.analytics.v1.TeamStats
	6,  // 23: tokman.analytics.v1.DashboardResponse.economics:type_name -> tokman.analytics.v1.GetEconomicsResponse
	12, // 24: tokman.analytics.v1.DashboardResponse.trends:type_name -> tokman.analytics.v1.TrendPoint
	9,  // 25: tokman.analytics.v1.DashboardResponse.top_filters:type_name -> tokman.analytics.v1.FilterMetric
	32, // 26: tokman.analytics.v1.DashboardResponse.user_stats:type_name -> tokman.analytics.v1.UserStats
	18, // 27: tokman.analytics.v1.DashboardResponse.projection:type_name -> tokman.analytics.v1.CostProjectionResponse
	0,  // 28: tokman.analytics.v1.AnalyticsService.Record:input_type -> tokman.analytics.v1.RecordRequest
	2,  // 29: tokman.analytics.v1.AnalyticsService.GetMetrics:input_type -> tokman.analytics.v1.GetMetricsRequest
	5,  // 30: tokman.analytics.v1.AnalyticsService.GetEconomics:input_type -> tokman.analytics.v1.GetEconomicsRequest
	7,  // 31: tokman.analytics.v1.AnalyticsService.GetFilterEffectiveness:input_type -> tokman.analytics.v1.FilterEffectivenessRequest
	10, // 32: tokman.analytics.v1.AnalyticsService.GetTrendAnalysis:input_type -> tokman.analytics.v1.TrendAnalysisRequest
	13, // 33: tokman.analytics.v1.AnalyticsService.GetTeamStats:input_type -> tokman.analytics.v1.TeamStatsRequest
	15, // 34: tokman.analytics.v1.AnalyticsService.GetUserStats:input_type -> tokman.analytics.v1.UserStatsRequest
	17, // 35: tokman.analytics.v1.AnalyticsService.GetCostProjection:input_type -> tokman.analytics.v1.CostProjectionRequest
	19, // 36: tokman.analytics.v1.AnalyticsService.GetAuditLogs:input_type -> tokman.analytics.v1.AuditLogsRequest
	22, // 37: tokman.analytics.v1.AnalyticsService.CreateTeam:input_type -> tokman.analytics.v1.CreateTeamRequest
	23, // 38: tokman.analytics.v1.AnalyticsService.GetTeam:input_type -> tokman.analytics.v1.GetTeamRequest
	25, // 39: tokman.analytics.v1.AnalyticsService.UpdateTeamBudget:input_type -> tokman.analytics.v1.UpdateTeamBudgetRequest
	26, // 40: tokman.analytics.v1.AnalyticsService.ListUsers:input_type -> tokman.analytics.v1.ListUsersRequest
	29, // 41: tokman.analytics.v1.AnalyticsService.GetDashboardData:input_type -> tokman.analytics.v1.DashboardRequest
	1,  // 42: tokman.analytics.v1.AnalyticsService.Record:output_type -> tokman.analytics.v1.RecordResponse
	3,  // 43: tokman.analytics.v1.AnalyticsService.GetMetrics:output_type -> tokman.analytics.v1.GetMetricsResponse
	6,  // 44: tokman.analytics.v1.AnalyticsService.GetEconomics:output_type -> tokman.analytics.v1.GetEconomicsResponse
	8,  // 45: tokman.analytics.v1.AnalyticsService.GetFilterEffectiveness:output_type -> tokman.analytics.v1.FilterEffectivenessResponse
	11, // 46: tokman.analytics.v1.AnalyticsService.GetTrendAnalysis:output_type -> tokman.analytics.v1.TrendAnalysisResponse
	14, // 47: tokman.analytics.v1.AnalyticsService.GetTeamStats:output_type -> tokman.analytics.v1.TeamStatsResponse
	16, // 48: tokman.analytics.v1.AnalyticsService.GetUserStats:output_type -> tokman.analytics.v1.UserStatsResponse
	18, // 49: tokman.analytics.v1.AnalyticsService.GetCostProjection:output_type -> tokman.analytics.v1.CostProjectionResponse
	20, // 50: tokman.analytics.v1.AnalyticsService.GetAuditLogs:output_type -> tokman.analytics.v1.AuditLogsResponse
	24, // 51: tokman.analytics.v1.AnalyticsService.CreateTeam:output_type -> tokman.analytics.v1.TeamResponse
	24, // 52: tokman.analytics.v1.AnalyticsService.GetTeam:output_type -> tokman.analytics.v1.TeamResponse
	24, // 53: tokman.analytics.v1.AnalyticsService.UpdateTeamBudget:output_type -> tokman.analytics.v1.TeamResponse
	27, // 54: tokman.analytics.v1.AnalyticsService.ListUsers:output_type -> tokman.analytics.v1.ListUsersResponse
	30, // 55: tokman.analytics.v1.AnalyticsService.GetDashboardData:output_type -> tokman.analytics.v1.DashboardResponse
	42, // [42:56] is the sub-list for method output_type
	28, // [28:42] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
